export interface Scene {
  sceneNumber: number;
  title: string;
  situation: string;
  mood: string;
  textKo: string;
}

export interface StoryTemplate {
  id: string;
  title: string;
  titleKo: string;
  synopsis: string;
  emoji: string;
  tag?: string;
  scenes: Scene[];
}

export const STORY_PRESETS: StoryTemplate[] = [
  // --- 오리지널 스토리 ---
  {
    id: "magic-forest",
    title: "Magic Forest Adventure",
    titleKo: "마법 숲 모험",
    synopsis: "빛나는 숲에서 요정 친구를 만나 비밀 정원을 발견하는 이야기",
    emoji: "🌲",
    scenes: [
      {
        sceneNumber: 1,
        title: "숲 입구",
        situation: "standing at the entrance of a magical glowing forest, curious and excited, sunlight filtering through the trees",
        mood: "wonder and excitement",
        textKo: "어느 날, 주인공은 반짝이는 빛이 흘러나오는 이상한 숲을 발견했어요.\n'이 숲엔 무언가 특별한 게 있을 것 같아!' 가슴이 두근두근, 첫 발을 내디뎠죠.",
      },
      {
        sceneNumber: 2,
        title: "요정과의 만남",
        situation: "discovering a tiny glowing fairy creature hiding behind a mushroom in the enchanted forest",
        mood: "surprise and delight",
        textKo: "숲속 깊은 곳에서 버섯 뒤에 숨어 있는 작은 요정을 만났어요.\n반짝이는 날개를 가진 요정은 수줍게 웃으며 손을 흔들었답니다.",
      },
      {
        sceneNumber: 3,
        title: "숲 속 모험",
        situation: "running joyfully through the magical forest with a newfound fairy friend, flowers blooming along the path",
        mood: "joy and adventure",
        textKo: "요정 친구와 함께 숲속을 뛰어다니자, 가는 길마다 꽃들이 활짝 피어났어요.\n웃음소리가 숲 전체에 울려 퍼졌지요.",
      },
      {
        sceneNumber: 4,
        title: "비밀의 장소",
        situation: "arriving at a secret hidden clearing with a sparkling pond and rainbow waterfall in the forest",
        mood: "awe and wonder",
        textKo: "오래오래 걷다 보니, 반짝이는 연못과 무지개 폭포가 있는 비밀 정원이 나타났어요.\n세상에, 이런 곳이 있었다니! 눈이 번쩍 뜨였어요.",
      },
      {
        sceneNumber: 5,
        title: "집으로",
        situation: "waving goodbye to forest friends at sunset, walking home happily with memories of the adventure",
        mood: "warmth and happiness",
        textKo: "해가 질 무렵, 숲속 친구들에게 손을 흔들며 집으로 돌아왔어요.\n오늘 하루는 평생 잊을 수 없는 소중한 추억이 되었답니다.",
      },
      {
        sceneNumber: 6,
        title: "다시 만날 약속",
        situation: "making a pinky promise with fairy friends to return, glowing twilight sky over the magical forest",
        mood: "warm promise and contentment",
        textKo: "요정 친구와 새끼손가락을 걸며 '꼭 다시 올게!'라고 약속했어요.\n따사로운 저녁 노을 아래, 가슴 가득 행복을 안고 돌아왔답니다.",
      },
    ],
  },
  {
    id: "ocean-adventure",
    title: "Under the Sea Exploration",
    titleKo: "바닷속 탐험",
    synopsis: "작은 잠수함을 타고 신비로운 바닷속 세계를 탐험하는 이야기",
    emoji: "🐠",
    scenes: [
      {
        sceneNumber: 1,
        title: "바닷가 출발",
        situation: "standing on a sunny beach, looking out at the sparkling ocean with a tiny yellow submarine nearby",
        mood: "curiosity and anticipation",
        textKo: "바닷가에 서서 반짝이는 바다를 바라보니, 작고 귀여운 노란 잠수함이 기다리고 있었어요.\n'자, 출발이야!' 용감하게 바다로 뛰어들었답니다.",
      },
      {
        sceneNumber: 2,
        title: "바다 속으로",
        situation: "diving underwater in a small submarine, colorful fish swimming all around, sunlight shining through the water",
        mood: "excitement and wonder",
        textKo: "잠수함을 타고 바다 속으로 들어가자, 온갖 물고기들이 반겨 주었어요.\n햇빛이 물속으로 쏟아져 마치 꿈속 같았지요.",
      },
      {
        sceneNumber: 3,
        title: "산호초 탐험",
        situation: "exploring a vibrant coral reef filled with tropical fish, sea turtles, and swaying sea plants",
        mood: "joy and discovery",
        textKo: "형형색색의 산호초 사이로 바다거북이와 열대어들이 살고 있었어요.\n그들과 함께 산호초 정원을 신나게 탐험했답니다.",
      },
      {
        sceneNumber: 4,
        title: "보물 발견",
        situation: "discovering an old treasure chest on the ocean floor surrounded by sea creatures, golden light glowing",
        mood: "amazement and delight",
        textKo: "바다 깊은 곳에서 금빛으로 빛나는 오래된 보물 상자를 발견했어요!\n바다 친구들이 빙 둘러서서 신기하게 바라보았어요.",
      },
      {
        sceneNumber: 5,
        title: "작별 인사",
        situation: "swimming back to the surface waving goodbye to ocean friends, sunset reflecting on the water",
        mood: "warmth and gratitude",
        textKo: "바다 친구들에게 손을 흔들고 수면 위로 올라오니, 석양이 물 위에 번지고 있었어요.\n'또 와야지!' 마음속에 다짐했답니다.",
      },
      {
        sceneNumber: 6,
        title: "바다의 선물",
        situation: "sitting on the beach at sunset holding a shiny seashell gift from ocean friends, smiling peacefully",
        mood: "peace and fond memories",
        textKo: "집으로 돌아와 바다 친구들이 준 조개를 귀에 대자, 파도 소리가 들렸어요.\n'내일도 또 오고 싶다!' 꿈속에서도 바다가 반짝였답니다.",
      },
    ],
  },
  {
    id: "star-journey",
    title: "Journey to the Stars",
    titleKo: "별나라 여행",
    synopsis: "작은 로켓을 타고 별나라를 여행하며 우주 친구들을 만나는 이야기",
    emoji: "⭐",
    scenes: [
      {
        sceneNumber: 1,
        title: "로켓 발사",
        situation: "sitting in a small colorful rocket on a launch pad at night, stars twinkling in the sky, ready to launch",
        mood: "excitement and bravery",
        textKo: "밤하늘 아래, 주인공은 색깔이 고운 작은 로켓에 탔어요.\n별들이 반짝반짝 응원하는 가운데, 용감하게 발사 버튼을 눌렀답니다!",
      },
      {
        sceneNumber: 2,
        title: "우주 비행",
        situation: "flying through outer space in the rocket, surrounded by colorful planets, stars, and galaxies",
        mood: "wonder and freedom",
        textKo: "우주를 날아다니니, 커다란 행성들과 아름다운 은하수가 펼쳐졌어요.\n이 넓은 우주에 혼자가 아니라는 생각에 가슴이 벅찼지요.",
      },
      {
        sceneNumber: 3,
        title: "별나라 도착",
        situation: "landing on a magical star planet with glowing ground, friendly star creatures waving hello",
        mood: "joy and amazement",
        textKo: "반짝이는 별 행성에 착륙하자, 빛나는 몸을 가진 별 친구들이 춤을 추며 반겨 주었어요.\n'환영해요, 지구에서 온 친구야!'",
      },
      {
        sceneNumber: 4,
        title: "별 친구들과",
        situation: "playing and dancing with cute alien friends on the star planet under a sky full of colorful nebulas",
        mood: "happiness and playfulness",
        textKo: "별 친구들과 함께 춤추고 노래하며 신나는 시간을 보냈어요.\n머리 위로는 오색 성운이 밤하늘을 수놓았답니다.",
      },
      {
        sceneNumber: 5,
        title: "지구로 귀환",
        situation: "flying back home in the rocket, Earth glowing below, waving goodbye to the star friends",
        mood: "nostalgia and contentment",
        textKo: "집으로 돌아오는 로켓 안에서 창밖을 내다보니, 별 친구들이 손을 흔들고 있었어요.\n지구의 파란빛이 점점 가까워졌지요.",
      },
      {
        sceneNumber: 6,
        title: "별빛 꿈",
        situation: "lying in bed at night gazing out the window at twinkling stars, holding a glowing star-shaped gift, smiling gently",
        mood: "dreamlike peace",
        textKo: "잠자리에 들어 창밖 별들을 바라보니, 별 친구들이 손을 흔드는 것 같았어요.\n별나라 여행은 꿈속에서도 계속되었답니다.",
      },
    ],
  },
  {
    id: "wizard-castle",
    title: "The Wizard's Castle",
    titleKo: "마법사의 성",
    synopsis: "마법사의 신비로운 성에서 처음으로 마법을 배우며 성장하는 이야기",
    emoji: "🏰",
    scenes: [
      {
        sceneNumber: 1,
        title: "성 발견",
        situation: "discovering a mysterious magical castle on top of a hill surrounded by clouds and glowing lights",
        mood: "curiosity and wonder",
        textKo: "언덕 너머로 구름에 둘러싸인 신비로운 성이 보였어요.\n반짝이는 빛이 새어 나오는 창문을 보자, 가슴이 두근거렸답니다.",
      },
      {
        sceneNumber: 2,
        title: "마법사와의 만남",
        situation: "meeting a kind old wizard with a long white beard inside the castle library full of magical books",
        mood: "awe and excitement",
        textKo: "성 안으로 들어서자, 흰 수염이 긴 친절한 마법사가 책으로 가득한 도서관에서 반겨 주었어요.\n'기다리고 있었단다, 꼬마 마법사야!'",
      },
      {
        sceneNumber: 3,
        title: "첫 마법 시도",
        situation: "trying the first magic spell with a tiny wand, colorful sparks flying everywhere in the wizard's workshop",
        mood: "determination and delight",
        textKo: "마법사의 작업실에서 처음으로 지팡이를 들었어요.\n주문을 외우자 알록달록한 불꽃이 사방으로 튀었답니다. '와, 신기해!'",
      },
      {
        sceneNumber: 4,
        title: "마법 성공",
        situation: "successfully casting a beautiful magic spell that creates rainbow butterflies filling the castle tower",
        mood: "pride and joy",
        textKo: "집중해서 주문을 외우자, 마침내 마법이 성공!\n탑 안 가득 무지개 나비들이 날아올랐어요. 마법사 할아버지도 박수를 쳤답니다.",
      },
      {
        sceneNumber: 5,
        title: "마법사가 된 아이",
        situation: "wearing a small wizard hat and cape, holding a glowing wand proudly in front of the magical castle",
        mood: "confidence and happiness",
        textKo: "작은 마법사 모자를 쓰고 빛나는 지팡이를 들고 성 앞에 섰어요.\n오늘부터는 나도 멋진 마법사랍니다!",
      },
      {
        sceneNumber: 6,
        title: "마법의 첫 걸음",
        situation: "walking down the hill from the wizard's castle at dusk, glowing wand in hand, looking ahead with determination and hope",
        mood: "hopeful and determined",
        textKo: "마법사의 성을 내려오며 환하게 빛나는 지팡이를 꼭 쥐었어요.\n이제 막 시작된 마법 여정, 앞으로 어떤 일이 기다릴까요?",
      },
    ],
  },
  {
    id: "animal-village",
    title: "The Animal Friends Village",
    titleKo: "동물 친구들의 마을",
    synopsis: "동물 마을을 방문해서 다양한 동물 친구들과 우정을 나누는 이야기",
    emoji: "🦊",
    scenes: [
      {
        sceneNumber: 1,
        title: "마을 도착",
        situation: "arriving at a charming village where animals live in cozy little houses, a friendly rabbit waving hello",
        mood: "delight and curiosity",
        textKo: "아기자기한 집들이 늘어선 동물 마을에 도착하자, 하얀 토끼가 폴짝폴짝 뛰어와 반겨 주었어요.\n'어서 와, 친구야! 우리 마을에 온 걸 환영해!'",
      },
      {
        sceneNumber: 2,
        title: "새 친구 만나기",
        situation: "being introduced to a group of friendly animals including a fox, bear, and deer in a sunny meadow",
        mood: "friendliness and joy",
        textKo: "햇살 가득한 들판에서 여우, 곰, 사슴 친구들을 만났어요.\n모두 환하게 웃으며 다가와 악수를 건넸답니다.",
      },
      {
        sceneNumber: 3,
        title: "함께 요리하기",
        situation: "cooking a big pot of vegetable soup with animal friends in a cozy kitchen, laughing and having fun",
        mood: "warmth and togetherness",
        textKo: "동물 친구들과 함께 아늑한 부엌에서 채소 수프를 끓였어요.\n보글보글 끓는 수프에서 맛있는 냄새가 솔솔 풍겼지요.",
      },
      {
        sceneNumber: 4,
        title: "마을 축제",
        situation: "dancing and celebrating at the animal village festival with colorful lanterns and music at night",
        mood: "happiness and excitement",
        textKo: "밤이 되자 마을 광장에 등불이 켜지고 축제가 시작되었어요.\n신나는 음악에 맞춰 모두 함께 춤을 추었답니다.",
      },
      {
        sceneNumber: 5,
        title: "작별 인사",
        situation: "hugging all the animal friends goodbye, holding a bouquet of flowers they gifted, smiling warmly",
        mood: "love and gratitude",
        textKo: "작별 인사를 하자 동물 친구들이 꽃다발을 선물해 주었어요.\n'또 놀러 와!' 따뜻한 포옹을 나누며 마을을 떠났답니다.",
      },
      {
        sceneNumber: 6,
        title: "편지 한 통",
        situation: "sitting at a desk writing a letter with colorful drawings of the animal village friends all around",
        mood: "warmth and fond memories",
        textKo: "집에 돌아와 동물 친구들에게 편지를 썼어요.\n'보고 싶어요, 꼭 다시 갈게요!' 편지마다 웃음이 가득 담겼답니다.",
      },
    ],
  },

  // --- 저작권 없는 고전 동화 ---
  {
    id: "cinderella",
    title: "Cinderella",
    titleKo: "신데렐라",
    synopsis: "요정 할머니의 도움으로 무도회에서 왕자를 만나는 신데렐라 이야기",
    emoji: "👠",
    tag: "고전 동화",
    scenes: [
      {
        sceneNumber: 1,
        title: "다락방의 소녀",
        situation: "a girl in simple clothes sitting alone in a dim attic room, looking out the window at stars, longing expression",
        mood: "longing and hope",
        textKo: "어두운 다락방에서 두 언니의 심부름을 하며 하루를 보내던 신데렐라는,\n창밖의 별을 보며 조용히 소원을 빌었어요.",
      },
      {
        sceneNumber: 2,
        title: "요정 할머니의 마법",
        situation: "a kind fairy godmother waving a magic wand, turning a pumpkin into a golden carriage, sparkling magic light everywhere",
        mood: "amazement and magic",
        textKo: "갑자기 요정 할머니가 나타나 지팡이를 휙 휘두르자,\n낡은 옷이 눈부신 드레스로, 호박이 황금 마차로 변했어요!\n'자, 무도회에 가거라!'",
      },
      {
        sceneNumber: 3,
        title: "왕자와의 춤",
        situation: "a girl in a shimmering ball gown dancing gracefully with a prince in a grand ballroom lit with chandeliers",
        mood: "romance and happiness",
        textKo: "왕궁 무도회에서 왕자님과 춤을 추는 신데렐라.\n무도회 홀은 온통 빛났고, 왕자님은 눈을 떼지 못했답니다.",
      },
      {
        sceneNumber: 4,
        title: "유리 구두",
        situation: "a girl rushing down palace stairs at midnight, leaving behind a sparkling glass slipper on the steps",
        mood: "urgency and suspense",
        textKo: "자정을 알리는 종소리에 황급히 달아나다 유리 구두 한 짝을 남겨 두었어요.\n계단을 뛰어 내려오는 신데렐라 뒤로 구두가 반짝였지요.",
      },
      {
        sceneNumber: 5,
        title: "유리 구두의 주인",
        situation: "a prince gently placing a glass slipper on a girl's foot, both smiling joyfully in a sunlit room",
        mood: "joy and relief",
        textKo: "유리 구두가 꼭 맞자, 왕자님은 환하게 웃으며 손을 내밀었어요.\n신데렐라는 마침내 행복한 공주가 되었답니다.",
      },
      {
        sceneNumber: 6,
        title: "영원히 행복하게",
        situation: "a princess and prince walking hand in hand through a sunlit palace garden, flowers blooming all around, happily ever after",
        mood: "joy and happily ever after",
        textKo: "왕자님과 함께 꽃이 만발한 정원을 거닐었어요.\n신데렐라는 그 후로도 오래오래 행복하게 살았답니다.",
      },
    ],
  },
  {
    id: "little-red-riding-hood",
    title: "Little Red Riding Hood",
    titleKo: "빨간 모자",
    synopsis: "빨간 모자를 쓴 소녀가 숲속에서 위험을 만나고 지혜롭게 헤쳐나가는 이야기",
    emoji: "🧺",
    tag: "고전 동화",
    scenes: [
      {
        sceneNumber: 1,
        title: "숲길을 걷는 소녀",
        situation: "a little girl wearing a bright red hood, walking through a sunny forest path carrying a picnic basket, cheerful and carefree",
        mood: "cheerful and innocent",
        textKo: "빨간 모자를 쓴 소녀는 할머니께 드릴 바구니를 들고 숲길을 걸었어요.\n엄마의 당부가 귓가에 맴돌았지요. '낯선 사람과 이야기하지 마렴!'",
      },
      {
        sceneNumber: 2,
        title: "늑대와의 만남",
        situation: "a large wolf smiling slyly, talking to a little girl with a red hood in the middle of the forest",
        mood: "suspense and curiosity",
        textKo: "숲 한가운데에서 커다란 늑대가 나타나 말을 걸었어요.\n'어디 가니, 꼬마야?' 빨간 모자는 용감하게 대답했어요.",
      },
      {
        sceneNumber: 3,
        title: "할머니 집",
        situation: "a little girl with a red hood standing beside a bed where a wolf in disguise as grandmother lies, looking suspicious",
        mood: "suspense and unease",
        textKo: "할머니 집에 도착했는데, 뭔가 이상했어요.\n귀가 너무 크고, 눈도 너무 크고, 이도 너무 컸어요!\n'할머니, 이가 왜 이렇게 커요?'",
      },
      {
        sceneNumber: 4,
        title: "나무꾼의 등장",
        situation: "a brave woodcutter bursting through the door to rescue a little girl and an old grandmother from a wolf",
        mood: "relief and bravery",
        textKo: "큰 소리로 도움을 청하자 나무꾼이 달려와 할머니와 빨간 모자를 구해 주었어요.\n늑대는 멀리멀리 달아났답니다.",
      },
      {
        sceneNumber: 5,
        title: "할머니와 함께",
        situation: "a little girl and a grandmother sitting together at a table sharing food and tea, smiling happily in a cozy cottage",
        mood: "warmth and relief",
        textKo: "할머니와 빨간 모자는 맛있는 음식을 나눠 먹으며 행복한 시간을 보냈어요.\n오늘 정말 무서웠지만, 할머니 곁에 있으니 괜찮았어요.",
      },
      {
        sceneNumber: 6,
        title: "더 현명해진 소녀",
        situation: "a girl with a red hood walking confidently through a sunny forest path with birds singing, wiser and braver",
        mood: "confidence and lesson learned",
        textKo: "그날 이후, 빨간 모자는 더욱 씩씩하고 현명한 소녀가 되었어요.\n숲길도 이제는 무섭지 않았답니다.",
      },
    ],
  },
  {
    id: "ant-and-grasshopper",
    title: "The Ant and the Grasshopper",
    titleKo: "개미와 베짱이",
    synopsis: "열심히 일하는 개미와 노래만 부르는 베짱이가 겨울을 통해 배우는 이솝 우화",
    emoji: "🦗",
    tag: "이솝 우화",
    scenes: [
      {
        sceneNumber: 1,
        title: "여름 들판",
        situation: "a grasshopper playing a tiny violin in the shade of a tree, while ants nearby carry food busily under the summer sun",
        mood: "carefree and contrast",
        textKo: "따사로운 여름 햇살 아래, 베짱이는 나무 그늘에서 노래를 불렀어요.\n가까운 곳에서 개미들은 땀을 흘리며 열심히 먹이를 옮겼답니다.",
      },
      {
        sceneNumber: 2,
        title: "개미의 충고",
        situation: "an ant carrying a large grain, looking up to talk to a relaxing grasshopper on a leaf, warm afternoon light",
        mood: "earnest and playful",
        textKo: "'이 더운 날에 일은 무슨!' 베짱이가 놀자고 손짓했지만,\n개미는 고개를 저으며 말했어요. '겨울이 오면 먹을 게 없을 거야.'",
      },
      {
        sceneNumber: 3,
        title: "가을이 오다",
        situation: "ants looking happily at a full food storage underground as autumn leaves fall outside, cozy warm atmosphere",
        mood: "satisfaction and preparedness",
        textKo: "가을이 되자 나뭇잎이 떨어지고 바람이 차가워졌어요.\n개미들은 창고 가득 모아 둔 식량을 보며 흐뭇해했답니다.",
      },
      {
        sceneNumber: 4,
        title: "차가운 겨울",
        situation: "a shivering thin grasshopper knocking on a small door in the snow, looking cold and hungry",
        mood: "remorse and cold",
        textKo: "눈이 내리는 겨울, 배고픈 베짱이가 개미 집 문을 두드렸어요.\n'배가 고파서요... 조금만 나눠 줄 수 있나요?'",
      },
      {
        sceneNumber: 5,
        title: "나눔의 마음",
        situation: "a kind ant welcoming a grasshopper inside a warm cozy home, offering food, both smiling together",
        mood: "kindness and gratitude",
        textKo: "마음씨 좋은 개미는 베짱이를 집 안으로 따뜻하게 맞이해 주었어요.\n'다음엔 함께 준비하자.' 베짱이는 고개를 끄덕이며 다짐했답니다.",
      },
      {
        sceneNumber: 6,
        title: "봄날의 약속",
        situation: "an ant and grasshopper working side by side together in a sunny spring meadow, flowers blooming all around",
        mood: "friendship and new beginning",
        textKo: "따뜻한 봄이 되자, 베짱이는 개미와 함께 열심히 일을 시작했어요.\n함께라면 무엇이든 할 수 있다는 것을 깨달았답니다.",
      },
    ],
  },
  {
    id: "tortoise-and-hare",
    title: "The Tortoise and the Hare",
    titleKo: "토끼와 거북이",
    synopsis: "빠른 토끼와 느린 거북이가 달리기 시합을 벌이는 이솝 우화",
    emoji: "🐢",
    tag: "이솝 우화",
    scenes: [
      {
        sceneNumber: 1,
        title: "토끼의 자만",
        situation: "a confident hare laughing and pointing at a slow tortoise on a forest path, other animals watching",
        mood: "arrogance and gentleness",
        textKo: "빠른 토끼는 언제나 느린 거북이를 놀렸어요.\n'거북아, 그렇게 느려서 어디에 쓰니?' 거북이는 조용히 웃기만 했지요.",
      },
      {
        sceneNumber: 2,
        title: "시합 시작",
        situation: "a hare and a tortoise at the starting line with cheering forest animals around them, race about to begin",
        mood: "excitement and anticipation",
        textKo: "숲속 동물들이 지켜보는 가운데 드디어 달리기 시합이 시작되었어요.\n토끼는 쏜살같이 앞서 나갔고, 거북이는 천천히 발을 내디뎠답니다.",
      },
      {
        sceneNumber: 3,
        title: "낮잠 자는 토끼",
        situation: "a hare sleeping comfortably under a shady tree, relaxed and oblivious, sunshine filtering through leaves",
        mood: "relaxed and overconfident",
        textKo: "한참 앞선 토끼는 그늘진 나무 아래서 쉬기로 했어요.\n'거북이가 따라오려면 한참 걸리겠지.' 눈꺼풀이 스르르 감겼어요.",
      },
      {
        sceneNumber: 4,
        title: "거북이의 꾸준함",
        situation: "a determined tortoise walking steadily past a sleeping hare on the road, step by step forward",
        mood: "perseverance and focus",
        textKo: "잠든 토끼 곁을 거북이가 조용히 지나쳐 갔어요.\n한 걸음 한 걸음, 포기하지 않고 꾸준히 걸어 나갔답니다.",
      },
      {
        sceneNumber: 5,
        title: "거북이의 승리",
        situation: "a tortoise crossing the finish line first, cheering animals celebrating, a surprised hare running in the background",
        mood: "triumph and lesson learned",
        textKo: "결승선에 거북이가 먼저 도착했어요!\n잠에서 깬 토끼는 깜짝 놀랐고, 동물 친구들은 거북이를 향해 환호성을 질렀답니다.",
      },
      {
        sceneNumber: 6,
        title: "진정한 친구",
        situation: "a hare and tortoise walking side by side together on a forest path, both smiling warmly as true friends",
        mood: "respect and friendship",
        textKo: "시합이 끝나고 토끼는 거북이에게 진심으로 사과했어요.\n그날부터 둘은 서로를 존중하는 진정한 친구가 되었답니다.",
      },
    ],
  },
  {
    id: "ugly-duckling",
    title: "The Ugly Duckling",
    titleKo: "미운 오리 새끼",
    synopsis: "남들과 달라 외로웠던 새끼 오리가 아름다운 백조가 되는 감동적인 이야기",
    emoji: "🦢",
    tag: "고전 동화",
    scenes: [
      {
        sceneNumber: 1,
        title: "다른 새끼 오리",
        situation: "a large gray duckling standing apart from small yellow ducklings near a pond, looking down sadly",
        mood: "loneliness and confusion",
        textKo: "어느 날 오리 엄마 품에서 커다란 알이 깨어났어요.\n형제들과는 다르게 크고 회색빛인 새끼 오리를 보며 모두 수군거렸지요.",
      },
      {
        sceneNumber: 2,
        title: "홀로 떠나다",
        situation: "a gray duckling walking alone along a misty river path, head hanging low, autumn leaves falling",
        mood: "sadness and loneliness",
        textKo: "'못생겼어, 저리 가!' 형제들의 놀림에 새끼 오리는 눈물을 흘리며 홀로 멀리 떠났어요.\n세상이 온통 차갑고 쓸쓸하게 느껴졌답니다.",
      },
      {
        sceneNumber: 3,
        title: "차가운 겨울",
        situation: "a lone gray duckling huddled by a frozen lake in winter snow, but looking up at the sky with hope",
        mood: "hardship and hope",
        textKo: "차가운 겨울 호수에서 홀로 떨고 있던 새끼 오리.\n하지만 봄이 오면 달라질 거라는 희망을 잃지 않았어요.",
      },
      {
        sceneNumber: 4,
        title: "아름다운 변신",
        situation: "a graceful white swan looking at its own reflection in a calm spring pond, surprised and delighted",
        mood: "wonder and self-discovery",
        textKo: "따뜻한 봄이 찾아오고, 물 위에 비친 자신의 모습을 보고 깜짝 놀랐어요.\n못생긴 오리가 아니라 눈부신 하얀 백조였답니다!",
      },
      {
        sceneNumber: 5,
        title: "백조 가족",
        situation: "beautiful white swans welcoming the young swan with open wings on a glistening lake, joyful reunion",
        mood: "joy and belonging",
        textKo: "다른 백조들이 다가와 날개를 펼치며 반겨 주었어요.\n마침내 자신이 있어야 할 곳을 찾은 하얀 백조는 눈물이 날 만큼 기뻤답니다.",
      },
      {
        sceneNumber: 6,
        title: "날아오르다",
        situation: "a beautiful white swan spreading wings wide and soaring up into a bright blue sky, free and magnificent",
        mood: "freedom and triumph",
        textKo: "힘차게 날개를 펼친 백조는 하늘 높이 날아올랐어요.\n있는 그대로의 나 자신이 얼마나 소중하고 아름다운지를 깨달았답니다.",
      },
    ],
  },
];

export const CUSTOM_STORY_ID = "custom";
